services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_API_USER: ${POSTGRES_API_USER}
      POSTGRES_API_PASSWORD: ${POSTGRES_API_PASSWORD}
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
    networks:
      - app-network
  api:
    build: .
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_API_USER: ${POSTGRES_API_USER}
      POSTGRES_API_PASSWORD: ${POSTGRES_API_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge